export const shops = [
  {
    id: "1",
    name: "French Laundry",
    address: "Jl. Citra Raya Made",
    image: "/images/coffee-shop.png",
    latitude: -6.302,
    longitude: 106.652,
    isOpen: true,
    isFavorite: true,
    category: "Jasa",
  },
  {
    id: "2",
    name: "Coffee & Code",
    address: "Jl. Tekno No. 21",
    latitude: -6.403,
    longitude: 109.653,
    image: "/images/coffee-shop.png",
    isOpen: false,
    isFavorite: false,
    category: "Makanan",
  },
  {
    id: "3",
    name: "Citra Boutique",
    address: "Citraland Boulevard",
    image: "/images/coffee-shop.png",
    latitude: -6.504,
    longitude: 107.654,
    isOpen: false,
    isFavorite: false,
    category: "Pakaian",
  },
];