import { Shop } from "@/types/shop";

export const shops: Shop[] = [
  {
    id: "1",
    name: "French Laundry",
    address: "Jl. Citra Raya Made",
    city: "Surabaya",
    description: "Premium laundry services with French quality standards",
    time: "08:00 - 18:00",
    image: "/images/coffee-shop.png",
    latitude: -6.302,
    longitude: 106.652,
    isOpen: true,
    isFavorite: true,
    category: "Jasa",
    catalog: [
      {
        id: 1,
        cat: "laundry",
        name: "Dry Cleaning",
        price: 15.0,
        image: "👔",
        badge: "Popular",
        popular: 95,
        sold: 250,
        date: 20230101,
      },
      {
        id: 2,
        cat: "laundry",
        name: "Wash & Fold",
        price: 8.5,
        image: "👕",
        popular: 85,
        sold: 180,
        date: 20230115,
      },
      {
        id: 3,
        cat: "laundry",
        name: "Premium Ironing",
        price: 12.0,
        image: "🎽",
        badge: "New",
        popular: 70,
        sold: 90,
        date: 20241101,
      },
    ],
    media: [
      {
        id: 101,
        title: "How We Clean Your Clothes",
        thumbnail:
          "https://images.unsplash.com/photo-1517677208171-0bc6725a3e60?w=600&fit=crop",
        duration: "2:30",
        views: "12.5K",
      },
      {
        id: 102,
        title: "Behind the Scenes - French Laundry",
        thumbnail:
          "https://images.unsplash.com/photo-1582735689369-4fe89db7114c?w=600&fit=crop",
        duration: "3:15",
        views: "8.2K",
      },
    ],
  },
  {
    id: "2",
    name: "Coffee & Code",
    address: "Jl. Tekno No. 21",
    city: "Surabaya",
    description: "A cozy workspace for developers with great coffee",
    time: "08:00 - 18:00",
    latitude: -6.403,
    longitude: 109.653,
    image: "/images/coffee-shop.png",
    isOpen: false,
    isFavorite: false,
    category: "Makanan",
    catalog: [
      {
        id: 11,
        cat: "espresso",
        name: "Espresso",
        price: 2.45,
        image: "☕",
        badge: "Popular",
        popular: 99,
        sold: 200,
        date: 20220101,
      },
      {
        id: 12,
        cat: "espresso",
        name: "Espresso Macchiato",
        price: 2.65,
        image: "☕",
        popular: 60,
        sold: 70,
        date: 20220202,
      },
      {
        id: 20,
        cat: "coldbrew",
        name: "Cold Brew",
        price: 2.95,
        image: "🥤",
        popular: 50,
        sold: 70,
        date: 20230101,
      },
      {
        id: 21,
        cat: "coldbrew",
        name: "Pumpkin Spice Cream Cold Brew",
        price: 4.25,
        image: "🥤",
        badge: "Season",
        popular: 80,
        sold: 120,
        date: 20241015,
      },
    ],
    media: [
      {
        id: 201,
        title: "Making the Perfect Espresso",
        thumbnail:
          "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=600&fit=crop",
        duration: "5:32",
        views: "15.2K",
      },
      {
        id: 202,
        title: "Latte Art Tutorial",
        thumbnail:
          "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&fit=crop",
        duration: "8:15",
        views: "22.5K",
      },
    ],
  },
  {
    id: "3",
    name: "Citra Boutique",
    address: "Citraland Boulevard",
    city: "Surabaya",
    description: "Fashion boutique with latest trends and styles",
    time: "08:00 - 18:00",
    image: "/images/coffee-shop.png",
    latitude: -6.504,
    longitude: 107.654,
    isOpen: false,
    isFavorite: false,
    category: "Pakaian",
    catalog: [
      {
        id: 31,
        cat: "clothing",
        name: "Summer Dress",
        price: 45.0,
        image: "👗",
        badge: "New",
        popular: 88,
        sold: 65,
        date: 20241110,
      },
      {
        id: 32,
        cat: "clothing",
        name: "Casual Blazer",
        price: 65.0,
        image: "🧥",
        popular: 75,
        sold: 45,
        date: 20241015,
      },
      {
        id: 33,
        cat: "accessories",
        name: "Designer Handbag",
        price: 120.0,
        image: "👜",
        badge: "Popular",
        popular: 92,
        sold: 110,
        date: 20240801,
      },
    ],
    media: [
      {
        id: 301,
        title: "2025 Fashion Trends",
        thumbnail:
          "https://images.unsplash.com/photo-1483985988355-763728e1935b?w=600&fit=crop",
        duration: "4:20",
        views: "18.3K",
      },
      {
        id: 302,
        title: "How to Style Your Wardrobe",
        thumbnail:
          "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?w=600&fit=crop",
        duration: "6:45",
        views: "25.1K",
      },
    ],
  },
];
